FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

ENV PYTHONUNBUFFERED=1

# Copy project files
COPY . .

# Command to run Celery worker
CMD ["celery", "-A", "ML_Module", "worker", "--loglevel=info"]
