FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements_celery.txt .
RUN pip install -r requirements_celery.txt

# Copy project files
COPY . .

# Command to run Celery worker
CMD ["celery", "-A", "ML_Module", "worker", "--loglevel=info"]
