services:
  ml_module:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml_module
    ports:
      - "8002:8000"  # Maps host port 8001 to container port 8000
    volumes:
      - .:/app
    networks:
      - shared_network
    environment:
      - DEBUG=True
    depends_on:
      - redis_ml

  redis_ml:
    image: redis:6-alpine
    container_name: redis_ml
    networks:
      - shared_network

  celery_worker_ml:
    build:
      context: .
      dockerfile: Dockerfile-celery
    container_name: celery_worker_ml
    volumes:
      - .:/app
    networks:
      - shared_network
    depends_on:
      - redis_ml
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

networks:
  shared_network:
    name: shared_network  # Create a shared external network