# Generated by Django 5.1.5 on 2025-01-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=50)),
                ('last_modified', models.DateField(blank=True, null=True)),
                ('last_used_for_prediction', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_prediction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cloud_key', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['stock_code', 'last_modified'],
            },
        ),
    ]
